# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\werty\PycharmProjects\untitled\ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(10, 20, 591, 471))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(620, 510, 171, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.buttons_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.buttons_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.buttons_layout.setSpacing(0)
        self.buttons_layout.setObjectName("buttons_layout")
        self.functions_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.functions_label.setFont(font)
        self.functions_label.setAlignment(QtCore.Qt.AlignCenter)
        self.functions_label.setObjectName("functions_label")
        self.buttons_layout.addWidget(self.functions_label)
        self.open_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_button.setObjectName("open_button")
        self.buttons_layout.addWidget(self.open_button)
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.buttons_layout.addWidget(self.save_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(620, 20, 171, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.parameters_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.parameters_layout.setContentsMargins(0, 0, 0, 0)
        self.parameters_layout.setObjectName("parameters_layout")
        self.brightness_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.brightness_label.setAlignment(QtCore.Qt.AlignCenter)
        self.brightness_label.setObjectName("brightness_label")
        self.parameters_layout.addWidget(self.brightness_label)
        self.brightness_dial = QtWidgets.QDial(self.verticalLayoutWidget_2)
        self.brightness_dial.setMaximum(100)
        self.brightness_dial.setProperty("value", 50)
        self.brightness_dial.setObjectName("brightness_dial")
        self.parameters_layout.addWidget(self.brightness_dial)
        self.contrast_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.contrast_label.setAlignment(QtCore.Qt.AlignCenter)
        self.contrast_label.setObjectName("contrast_label")
        self.parameters_layout.addWidget(self.contrast_label)
        self.contrast_dial = QtWidgets.QDial(self.verticalLayoutWidget_2)
        self.contrast_dial.setProperty("value", 50)
        self.contrast_dial.setObjectName("contrast_dial")
        self.parameters_layout.addWidget(self.contrast_dial)
        self.color_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_label.setObjectName("color_label")
        self.parameters_layout.addWidget(self.color_label)
        self.color_dial = QtWidgets.QDial(self.verticalLayoutWidget_2)
        self.color_dial.setProperty("value", 50)
        self.color_dial.setObjectName("color_dial")
        self.parameters_layout.addWidget(self.color_dial)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 510, 591, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.filterinfo_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.filterinfo_layout.setContentsMargins(0, 0, 0, 0)
        self.filterinfo_layout.setObjectName("filterinfo_layout")
        self.filters_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filters_label.setFont(font)
        self.filters_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filters_label.setObjectName("filters_label")
        self.filterinfo_layout.addWidget(self.filters_label)
        self.filters_layout = QtWidgets.QHBoxLayout()
        self.filters_layout.setObjectName("filters_layout")
        self.gotham_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.gotham_button.setObjectName("gotham_button")
        self.filters_layout.addWidget(self.gotham_button)
        self.kelvin_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.kelvin_button.setObjectName("kelvin_button")
        self.filters_layout.addWidget(self.kelvin_button)
        self.lomo_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.lomo_button.setObjectName("lomo_button")
        self.filters_layout.addWidget(self.lomo_button)
        self.nashville_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.nashville_button.setObjectName("nashville_button")
        self.filters_layout.addWidget(self.nashville_button)
        self.filterinfo_layout.addLayout(self.filters_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filters v0.1"))
        self.image_label.setText(_translate("MainWindow", "Чтобы приступить к обработке, откройте изображение."))
        self.functions_label.setText(_translate("MainWindow", "Функции"))
        self.open_button.setText(_translate("MainWindow", "Открыть"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
        self.brightness_label.setText(_translate("MainWindow", "Яркость"))
        self.contrast_label.setText(_translate("MainWindow", "Контраст"))
        self.color_label.setText(_translate("MainWindow", "Насыщенность"))
        self.filters_label.setText(_translate("MainWindow", "Фильтры"))
        self.gotham_button.setText(_translate("MainWindow", "Gotham"))
        self.kelvin_button.setText(_translate("MainWindow", "Kelvin"))
        self.lomo_button.setText(_translate("MainWindow", "LOMO"))
        self.nashville_button.setText(_translate("MainWindow", "Отмена"))

